(function () {
  const LANG_KEY = "river-lang";
  const DEFAULT_LANG = "en";
  
  const translations = {
    en: {
      "skip-link": "Skip to main content",
      "nav-gallery": "Gallery",
      "nav-customize": "Customize",
      "nav-checkout": "Order",
      "nav-account": "My Orders",
      "nav-cart": "Cart",
      "nav-how-it-works": "How It Works",
      "nav-specs": "Specs",
      "nav-contact": "Contact",
      "btn-login": "Login",
      "btn-signup": "Sign Up",
      "btn-logout": "Logout",
      "theme-toggle": "Toggle light/dark theme",
      "hero-eyebrow": "Memories at Your Fingertips",
      "hero-title": "Turn Your\n<span class=\"hero__accent\">Photos into Art</span>",
      "hero-lead": "Every photo tells a story. Transform your precious memories into tangible 3D fridge magnets with AI magic. Let those warm moments come alive in your everyday life.",
      "hero-action-1": "Create Yours Now",
      "hero-action-2": "Our Story",
      "story-title": "Every Magnet Tells a Story",
      "story-p1": "In this fast-paced world, our lives are filled with countless photos, yet most of them lie forgotten in our phone galleries.",
      "story-p2": "<strong>River Magnets</strong> was born from a simple wish: <em>to make every precious moment visible, touchable, and cherished forever.</em>",
      "story-p3": "We believe a great photo is more than pixels - it carries laughter, tears, love, and memories. Through advanced AI technology and 3D printing, we transform these emotions into art you can hold in your hand.",
      "story-p4": "Whether it's your baby's first steps, your pet's adorable moments, a breathtaking sunset from your travels, or a sweet portrait with your loved one - every story deserves to be remembered.",
      "story-feature-1-title": "AI Artistic Styles",
      "story-feature-1-desc": "Choose from Van Gogh's Starry Night, Monet's Impressionism, Studio Ghibli's whimsical style... let AI breathe artistic life into your photos",
      "story-feature-2-title": "Unique Customization",
      "story-feature-2-desc": "Control every detail from corner radius to border design. Create a one-of-a-kind masterpiece that reflects your style",
      "story-feature-3-title": "Meaningful Gifts",
      "story-feature-3-desc": "Perfect gifts for parents, anniversary surprises for partners, and cherished keepsakes for growing children",
      "gallery-title": "Gallery",
      "gallery-intro": "Behind every magnet lies a heartfelt story. They are not just decorations, but carriers of emotion and testaments of love.",
      "gallery-item-1-title": "Family Moments",
      "gallery-item-1-desc": "Transform family portraits into warm kitchen decor. Every time you open the fridge, it's a happy memory.",
      "gallery-item-2-title": "Pet Love",
      "gallery-item-2-desc": "Capture your furry friend's cutest moments forever on your fridge. A daily dose of joy awaits.",
      "gallery-item-3-title": "Travel Memories",
      "gallery-item-3-desc": "Beautiful landscapes and delicious cuisines from your journeys. Let travel memories become the most special decoration in your home.",
      "gallery-item-4-title": "Artistic Styles",
      "gallery-item-4-desc": "Transform photos into watercolor, oil painting, clay and more artistic styles with AI. Create truly unique fridge magnets.",
      "how-title": "How It Works",
      "step-1-title": "Upload Photo",
      "step-1-desc": "Choose a meaningful photo. Supports JPG, PNG, WEBP and other common formats.",
      "step-2-title": "Choose Style",
      "step-2-desc": "Transform your photo with AI. Explore styles from 3D cartoon to watercolor painting.",
      "step-3-title": "AI Generate",
      "step-3-desc": "Choose a 3D style and shape. AI will transform your photo into a realistic fridge magnet on display.",
      "step-4-title": "Download & Order",
      "step-4-desc": "Download the preview and contact us to place your order. Your unique magnet is on the way!",
      "customizer-title": "Create Your Magnet",
      "customizer-intro": "Upload your photo, choose a style, and let AI transform it into a unique artistic masterpiece. Compare up to 3 previews, then add to cart.",
      "wizard-step-1": "Upload",
      "wizard-step-2": "Style",
      "wizard-step-3": "Generate",
      "wizard-step-4": "Select",
      "wizard-step-5": "Order",
      "wizard-upload-hint": "Use a clear photo with a visible face or pet. This becomes your magnet design.",
      "wizard-generate-hint": "Generate up to 3 options to compare. Each takes about 15–30 seconds.",
      "wizard-confirm-hint": "Select your favorite option above, then continue to add to cart.",
      "wizard-confirm-agree": "I confirm this preview for production. I understand minor color/crop differences may occur.",
      "wizard-order-ready": "Preview selected! Choose size and add to cart.",
      "wizard-go-checkout": "Go to Checkout",
      "btn-add-to-cart": "Add to Cart",
      "size-picker-label": "Size",
      "size-mini": "Mini (5×6 cm)",
      "size-standard": "Standard (8×10 cm)",
      "size-large": "Large (12×15 cm)",
      "discount-promo": "Buy 2+ save 5% · 4+ save 10% · 7+ save 15%",
      "discount-promo-hint": "Add 1 more item — save 5%!",
      "discount-applied": "Enjoy {n}% multi-item discount",
      "discount-tier-1": "2–3 items: 5% off",
      "discount-tier-2": "4–6 items: 10% off",
      "discount-tier-3": "7+ items: 15% off",
      "cart-empty": "Your cart is empty. Select a preview and add it here.",
      "cart-subtotal": "Subtotal",
      "cart-discount": "Multi-item discount",
      "cart-total": "Total",
      "cart-drawer-title": "Shopping Cart",
      "cart-drawer-checkout": "Go to Checkout",
      "cart-bar-title": "Design ready",
      "cart-bar-hint": "Pick a size, then add to cart. Confirm at checkout.",
      "cart-bar-view": "View Cart",
      "cart-need-confirm": "Please select a preview option first (Step 4).",
      "wizard-back": "Back",
      "wizard-next": "Next",
      "wizard-need-photo": "Please upload a photo first (Step 1).",
      "wizard-need-style": "Please select a style first (Step 2).",
      "wizard-need-generate": "Please generate a preview first.",
      "wizard-need-selection": "Please select a preview option above.",
      "order-need-confirm": "Please confirm the preview for production before placing your order.",
      "preview-tab-fridge": "On Fridge",
      "preview-tab-product": "Product Close-up",
      "scale-label-fridge": "Fridge (reference)",
      "scale-label-magnet": "Magnet (product)",
      "scale-label-ratio": "Magnet / Fridge height",
      "scale-magnet-nominal": "≈ 8 × 10 cm",
      "scale-bg-removed": "✓ Background removed in preview",
      "progress-preparing": "Preparing image...",
      "progress-ai": "Sending to AI (15–30 sec)...",
      "progress-mask": "Removing background & compositing...",
      "progress-done": "Done!",
      "btn-confirm-design": "Confirm Design",
      "checkout-no-design": "Your cart is empty. Add items from the customizer first.",
      "dropzone-text": "<strong>Click or drag image here</strong>",
      "dropzone-hint": "Supports JPG, PNG, WEBP, GIF",
      "status-no-image": "No image selected yet.",
      "status-photo-loaded": "Photo loaded. Choose type, style and generate!",
      "status-preview-ready": "Preview ready. Compare options or add to cart.",
      "status-option-ready": "Option ready! Compare up to 3, then add to cart.",
      "ai-legend": "Choose Your Style",
      "ai-desc": "Select an artistic style to transform your photo",
      "style-cat-3d": "3D Epoxy Styles",
      "style-cat-art": "Artistic Flat Styles",
      "dim-label": "Type",
      "dim-3d": "3D Magnet",
      "dim-2d": "2D Magnet",
      "style-3d-cartoon": "Cute Cartoon",
      "style-3d-cartoon-desc": "Epoxy dome · contour cut",
      "style-3d-chibi": "Chibi 3D",
      "style-3d-chibi-desc": "Big-head chibi · epoxy dome",
      "style-flat-outline": "Flat Outline",
      "style-flat-outline-desc": "2D print · clean outline",
      "style-clay": "Clay World",
      "style-clay-desc": "Claymation · epoxy dome",
      "style-anime": "Anime Style",
      "style-anime-desc": "Japanese anime · epoxy dome",
      "style-resin": "Resin Art",
      "style-resin-desc": "Crystal resin collectible",
      "style-ceramic": "Ceramic Art",
      "style-ceramic-desc": "Glazed ceramic texture",
      "style-watercolor": "Watercolor",
      "style-watercolor-desc": "Soft watercolor washes",
      "style-oil-painting": "Oil Painting",
      "style-oil-painting-desc": "Classic oil brush strokes",
      "style-pop-art": "Pop Art",
      "style-pop-art-desc": "Bold comic pop art",
      "style-pixel-art": "Pixel Art",
      "style-pixel-art-desc": "Retro 8-bit game style",
      "btn-ai-generate": "Generate My Magnet",
      "btn-download": "Download Preview PNG",
      "btn-login-to-download": "Login to Download",
      "preview-label": "Magnet preview",
      "preview-note": "Preview uses real-world scale (91×178 cm fridge, 9×11 cm magnet). Dimensions shown on canvas. Background is removed for magnet display.",
      "specs-title": "Product Features",
      "specs-intro": "Every magnet is meticulously crafted to ensure vibrant colors, sharp details, and lasting durability.",
      "spec-card-1-title": "Premium Materials",
      "spec-card-1-desc": "Soft magnetic backing + high-definition printed surface. Smooth as glass, sticks securely and removes cleanly without residue.",
      "spec-card-2-title": "Vibrant Colors",
      "spec-card-2-desc": "Professional printing technology ensures vivid colors that resist fading. Your photos stay sharp and lively for years.",
      "spec-card-3-title": "Custom Shapes",
      "spec-card-3-desc": "Choose from classic rounded rectangles or create custom shapes. Make your magnet truly one-of-a-kind.",
      "contact-title": "Contact Us",
      "contact-intro": "Tell your story through photos and make every everyday moment special. Ready to create? Contact us and share your vision.",
      "contact-card-1-title": "Email",
      "contact-card-1-desc": "hello@rivermagnets.com",
      "contact-form-name-label": "Name *",
      "contact-form-email-label": "Email *",
      "contact-form-subject-label": "Subject",
      "contact-form-message-label": "Message *",
      "contact-form-message-placeholder": "How can we help you? Tell us about your vision...",
      "btn-send-message": "Send Message",
      "auth-tab-login": "Login",
      "auth-tab-signup": "Sign Up",
      "login-username-label": "Username or Email",
      "login-password-label": "Password",
      "btn-login-submit": "Login",
      "signup-username-label": "Username",
      "signup-email-label": "Email",
      "signup-password-label": "Password",
      "signup-confirm-label": "Confirm Password",
      "btn-signup-submit": "Sign Up",
      "footer-text": "© <span data-year></span> River Magnets · Previews for display only",
      "checkout-title": "Place Your Order",
      "checkout-intro": "Review your cart, enjoy multi-item discounts, and submit one order for all designs.",
      "checkout-summary-title": "Order Summary",
      "checkout-shipping-title": "Shipping Details",
      "checkout-product": "Custom Photo Magnet",
      "order-quantity-label": "Quantity *",
      "order-size-label": "Size",
      "order-size-standard": "Standard (8x10 cm)",
      "order-size-large": "Large (12x15 cm)",
      "order-size-mini": "Mini (5x6 cm)",
      "order-name-label": "Full Name *",
      "order-email-label": "Email",
      "order-address-label": "Address *",
      "order-city-label": "City *",
      "order-state-label": "State / Province",
      "order-zip-label": "ZIP / Postal Code",
      "order-country-label": "Country *",
      "order-notes-label": "Special Notes",
      "order-notes-placeholder": "Any special requirements or notes for your order...",
      "btn-place-order": "Place Order",
      "btn-placing-order": "Placing order...",
      "checkout-addons-title": "Optional add-ons",
      "addon-gift-box": "Gift box packaging (+$3.99)",
      "addon-pro-retouch": "Pro retouch & cutout review (+$4.99)",
      "addon-rush": "Rush production 24h (+$7.99)",
      "cart-addons": "Add-ons",
      "cart-shipping": "Shipping",
      "shipping-note": "Free US shipping on orders $35+. Otherwise $4.99 flat rate.",
      "btn-pay-card": "Pay with Card",
      "payment-success-title": "Payment successful!",
      "payment-success-body": "Thank you! Order",
      "payment-success-email": "We'll email your receipt and shipping updates shortly.",
      "payment-cancelled": "Payment cancelled. Your order was not charged.",
      "faq-title": "FAQ",
      "faq-q1": "How long does production take?",
      "faq-a1": "Standard orders ship within 2–3 business days after payment. Rush add-on targets 24h production.",
      "faq-q2": "Will the magnet look exactly like the preview?",
      "faq-a2": "We match your confirmed design. Minor color and crop differences may occur due to printing — the preview is your approval reference.",
      "faq-q3": "What is your return policy?",
      "faq-a3": "Defective or damaged items: free replacement within 14 days. Custom items cannot be returned unless we made an error.",
      "faq-q4": "What sizes are available?",
      "faq-a4": "Mini 5×6 cm ($7.99), Standard 8×10 cm ($11.99), Large 12×15 cm ($16.99). Multi-item discounts apply automatically.",
      "faq-q5": "How does payment work?",
      "faq-a5": "Secure card checkout via Stripe when enabled. Otherwise we confirm your order by email with payment instructions.",
      "faq-compare-link": "See how River Magnets compares →",
      "checkout-note": "By placing your order, you agree to our Terms of Service. We will contact you via email with payment and shipping details.",
      "cookie-text": "We use cookies to enhance your experience. By continuing, you agree to our use of cookies.",
      "cookie-accept": "Accept",
      "privacy-link": "Privacy Policy"
    },
    zh: {
      "skip-link": "跳到主要内容",
      "nav-gallery": "案例",
      "nav-customize": "在线定制",
      "nav-how-it-works": "如何定制",
      "nav-specs": "规格说明",
      "nav-contact": "联系",
      "btn-login": "登录",
      "btn-signup": "注册",
      "btn-logout": "退出",
      "theme-toggle": "切换浅色/深色主题",
      "hero-eyebrow": "让回忆触手可及",
      "hero-title": "把爱\n<span class=\"hero__accent\">贴在心上</span>",
      "hero-lead": "一张照片，一个故事。我们用AI魔法将你最珍贵的瞬间变成触手可及的立体冰箱贴，让那些温暖的回忆不再沉睡在相册里，而是每天陪伴在你的生活中。",
      "hero-action-1": "创造专属回忆",
      "hero-action-2": "了解我们的故事",
      "story-title": "每一个冰箱贴，都是爱的形状",
      "story-p1": "在这个快节奏的时代，我们的生活被无数照片填满，但它们大多沉睡在手机相册里，渐渐被遗忘。",
      "story-p2": "<strong>River 冰箱贴</strong> 诞生于这样一个简单的愿望：<em>让每一个珍贵瞬间，都能被看见、被触摸、被珍藏。</em>",
      "story-p3": "我们相信，一张好照片不仅仅是像素的组合，它承载着欢笑、泪水、爱与思念。通过先进的AI技术和3D打印工艺，我们将这些情感凝固成可以握在手心的艺术品。",
      "story-p4": "无论是宝宝第一次蹒跚学步的模样、毛孩子撒娇的可爱瞬间、旅行途中的落日余晖，还是与爱人的甜蜜合照——每一个故事都值得被铭记。",
      "story-feature-1-title": "AI艺术升华",
      "story-feature-1-desc": "选择梵高的星空、莫奈的印象派、宫崎骏的童话风格...让AI为你的照片赋予艺术生命",
      "story-feature-2-title": "独一无二定制",
      "story-feature-2-desc": "从圆角弧度到边框细节，每一个参数都由你掌控，打造专属于你的艺术品",
      "story-feature-3-title": "情感传递礼物",
      "story-feature-3-desc": "送给父母的暖心礼物、送给爱人的纪念日惊喜、送给孩子的成长记录",
      "gallery-title": "爱的纪念册",
      "gallery-intro": "每一个冰箱贴背后，都藏着一个动人的故事。它们不只是装饰品，更是情感的载体，是爱的见证。",
      "gallery-item-1-title": "家庭合影",
      "gallery-item-1-desc": "把全家福或亲子照变成温馨的厨房角落，每次开冰箱都是一次幸福回忆。",
      "gallery-item-2-title": "萌宠时刻",
      "gallery-item-2-desc": "猫咪狗狗的可爱瞬间，永远定格在冰箱上，治愈每一次疲惫的下班时光。",
      "gallery-item-3-title": "旅行记忆",
      "gallery-item-3-desc": "去过的美丽风景、吃过的地道美食，让旅途的回忆成为家中最特别的装饰。",
      "gallery-item-4-title": "艺术风格",
      "gallery-item-4-desc": "通过AI技术，将照片转换成水彩、油画、粘土等艺术风格，打造别具一格的冰箱贴。",
      "how-title": "如何定制",
      "step-1-title": "上传照片",
      "step-1-desc": "选择一张有意义的照片，支持 JPG、PNG、WEBP 等常见格式。",
      "step-2-title": "选择风格",
      "step-2-desc": "使用 AI 一键转换照片风格，从3D卡通到水彩画，多种创意玩法等你探索。",
      "step-3-title": "AI 生成",
      "step-3-desc": "选择3D风格和形状，AI将把你的照片转换成展示在冰箱上的逼真冰箱贴效果。",
      "step-4-title": "下载下单",
      "step-4-desc": "下载预览图，联系客服确认下单，等待独一无二的冰箱贴送到家。",
      "customizer-title": "开始创作你的冰箱贴",
      "customizer-intro": "上传你的照片，选择喜欢的风格，让 AI 转换成独特的艺术效果。最多对比 3 个预览，满意后加入购物车。",
      "wizard-step-1": "上传",
      "wizard-step-2": "风格",
      "wizard-step-3": "生成",
      "wizard-step-4": "选择",
      "wizard-step-5": "下单",
      "wizard-upload-hint": "请使用人脸或宠物清晰可见的照片，这将作为冰箱贴设计基础。",
      "wizard-generate-hint": "最多生成 3 个方案对比，每次约需 15–30 秒。",
      "wizard-confirm-hint": "在上方选择最满意的方案，然后继续加入购物车。",
      "wizard-confirm-agree": "我确认此预览用于生产，并理解成品可能存在轻微色差或裁切差异。",
      "wizard-order-ready": "已选好预览！请选择尺寸并加入购物车。",
      "wizard-go-checkout": "前往下单",
      "btn-add-to-cart": "加入购物车",
      "size-picker-label": "尺寸",
      "size-mini": "迷你 (5×6 cm)",
      "size-standard": "标准 (8×10 cm)",
      "size-large": "大号 (12×15 cm)",
      "discount-promo": "满2件享95折 · 满4件享9折 · 满7件享85折",
      "discount-promo-hint": "再买1件即可享95折！",
      "discount-applied": "已享 {n}% 多件优惠",
      "discount-tier-1": "2–3 件：95折",
      "discount-tier-2": "4–6 件：9折",
      "discount-tier-3": "7 件以上：85折",
      "cart-empty": "购物车为空。请选择预览方案后点击「加入购物车」。",
      "cart-subtotal": "小计",
      "cart-discount": "多件优惠",
      "cart-total": "合计",
      "cart-drawer-title": "购物车",
      "cart-drawer-checkout": "前往结账",
      "cart-bar-title": "设计已就绪",
      "cart-bar-hint": "选好尺寸后加入购物车，下单时再确认。",
      "cart-bar-view": "查看购物车",
      "cart-need-confirm": "请先在第 4 步选择一个预览方案。",
      "wizard-back": "上一步",
      "wizard-next": "下一步",
      "wizard-need-photo": "请先上传照片（第 1 步）。",
      "wizard-need-style": "请先选择风格（第 2 步）。",
      "wizard-need-generate": "请先生成预览。",
      "wizard-need-selection": "请先在上方选择一个预览方案。",
      "order-need-confirm": "提交订单前请确认预览用于生产。",
      "preview-tab-fridge": "冰箱场景",
      "preview-tab-product": "产品特写",
      "scale-label-fridge": "冰箱（参照）",
      "scale-label-magnet": "冰箱贴（产品）",
      "scale-label-ratio": "冰箱贴 / 冰箱高度比",
      "scale-magnet-nominal": "≈ 8 × 10 cm",
      "scale-bg-removed": "✓ 预览已扣除背景",
      "progress-preparing": "准备图片...",
      "progress-ai": "AI 生成中（约 15–30 秒）...",
      "progress-mask": "抠图并合成预览...",
      "progress-done": "完成！",
      "btn-confirm-design": "确认设计",
      "checkout-no-design": "购物车为空，请先在定制器中加入商品。",
      "dropzone-text": "<strong>点击或拖放图片到此处</strong>",
      "dropzone-hint": "支持 JPG、PNG、WEBP、GIF",
      "status-no-image": "尚未选择图片。",
      "status-photo-loaded": "照片已加载。请选择类型、风格并生成！",
      "status-preview-ready": "预览已就绪。可对比方案或加入购物车。",
      "status-option-ready": "方案已生成！最多对比 3 个，然后加入购物车。",
      "ai-legend": "选择你的风格",
      "ai-desc": "选择一种艺术风格来转换你的照片",
      "style-cat-3d": "3D 滴胶立体",
      "style-cat-art": "艺术平面风格",
      "dim-label": "类型",
      "dim-3d": "3D 磁贴",
      "dim-2d": "2D 磁贴",
      "style-3d-cartoon": "可爱卡通",
      "style-3d-cartoon-desc": "滴胶立体 · 异形切割",
      "style-3d-chibi": "Q版大头立体",
      "style-3d-chibi-desc": "大头 Q 版 · 滴胶立体",
      "style-flat-outline": "平面描边",
      "style-flat-outline-desc": "清晰描边 · 哑光印刷",
      "style-clay": "黏土世界",
      "style-clay-desc": "黏土动画风 · 滴胶立体",
      "style-anime": "动漫风格",
      "style-anime-desc": "日系动漫 · 滴胶立体",
      "style-resin": "树脂艺术",
      "style-resin-desc": "透明树脂收藏级",
      "style-ceramic": "陶瓷艺术",
      "style-ceramic-desc": "釉面陶瓷质感",
      "style-watercolor": "水彩画",
      "style-watercolor-desc": "柔和水彩晕染",
      "style-oil-painting": "油画",
      "style-oil-painting-desc": "经典油画笔触",
      "style-pop-art": "波普艺术",
      "style-pop-art-desc": "鲜明波普漫画风",
      "style-pixel-art": "像素艺术",
      "style-pixel-art-desc": "复古像素游戏风",
      "btn-ai-generate": "生成我的冰箱贴",
      "btn-download": "下载预览 PNG",
      "btn-login-to-download": "登录后下载",
      "preview-label": "冰箱贴效果图预览",
      "preview-note": "预览按真实比例（冰箱 91×178 cm，冰箱贴 9×11 cm），画布上标注尺寸。磁铁区域已自动抠图去背景。",
      "specs-title": "产品特点",
      "specs-intro": "每一枚冰箱贴都经过精心制作，确保色彩饱满、细节清晰、经久耐用。",
      "spec-card-1-title": "优质材质",
      "spec-card-1-desc": "软磁背部 + 高清印刷面层，表面光滑如镜面，轻轻一贴就能牢牢吸附，取下也不留痕迹。",
      "spec-card-2-title": "持久色彩",
      "spec-card-2-desc": "采用专业印刷技术，色彩鲜艳不易褪色。即使长时间使用，依然能保持照片的清晰与生动。",
      "spec-card-3-title": "个性定制",
      "spec-card-3-desc": "支持各种尺寸和形状，从经典圆角矩形到创意异形，让你的冰箱贴与众不同。",
      "contact-title": "联系我们",
      "contact-intro": "有任何问题或定制需求？欢迎随时联系我们，我们很乐意为您服务。",
      "contact-card-1-title": "邮箱",
      "contact-card-1-desc": "hello@rivermagnets.com",
      "contact-form-name-label": "姓名 *",
      "contact-form-email-label": "邮箱 *",
      "contact-form-subject-label": "主题",
      "contact-form-message-label": "留言 *",
      "contact-form-message-placeholder": "有什么可以帮你的？告诉我们你的想法...",
      "btn-send-message": "发送消息",
      "auth-tab-login": "登录",
      "auth-tab-signup": "注册",
      "login-username-label": "用户名或邮箱",
      "login-password-label": "密码",
      "btn-login-submit": "登录",
      "signup-username-label": "用户名",
      "signup-email-label": "邮箱",
      "signup-password-label": "密码",
      "signup-confirm-label": "确认密码",
      "btn-signup-submit": "注册",
      "footer-text": "© <span data-year></span> River 冰箱贴 · 预览图仅供展示",
      "nav-checkout": "下单",
      "nav-account": "我的订单",
      "nav-cart": "购物车",
      "checkout-title": "提交订单",
      "checkout-intro": "查看购物车、享受多件优惠，一次提交全部设计订单。",
      "checkout-summary-title": "订单摘要",
      "checkout-shipping-title": "收货信息",
      "checkout-product": "定制照片冰箱贴",
      "order-quantity-label": "数量 *",
      "order-size-label": "尺寸",
      "order-size-standard": "标准 (8x10 cm)",
      "order-size-large": "大号 (12x15 cm)",
      "order-size-mini": "迷你 (5x6 cm)",
      "order-name-label": "收货人姓名 *",
      "order-email-label": "邮箱",
      "order-address-label": "收货地址 *",
      "order-city-label": "城市 *",
      "order-state-label": "省份/州",
      "order-zip-label": "邮政编码",
      "order-country-label": "国家 *",
      "order-notes-label": "特殊要求",
      "order-notes-placeholder": "如有任何特殊要求或备注，请在此说明...",
      "btn-place-order": "提交订单",
      "btn-placing-order": "提交中...",
      "checkout-addons-title": "可选加购",
      "addon-gift-box": "礼盒包装（+$3.99）",
      "addon-pro-retouch": "专业抠图复核（+$4.99）",
      "addon-rush": "加急生产 24 小时（+$7.99）",
      "cart-addons": "加购项",
      "cart-shipping": "运费",
      "shipping-note": "美国订单满 $35 免运费，否则统一 $4.99。",
      "btn-pay-card": "信用卡支付",
      "payment-success-title": "支付成功！",
      "payment-success-body": "感谢下单！订单",
      "payment-success-email": "我们将通过邮件发送收据和物流更新。",
      "payment-cancelled": "已取消支付，未扣款。",
      "faq-title": "常见问题",
      "faq-q1": "生产需要多久？",
      "faq-a1": "标准订单付款后 2–3 个工作日发货。加急选项目标 24 小时内生产。",
      "faq-q2": "实物会和预览一模一样吗？",
      "faq-a2": "我们按你确认的设计生产。印刷可能存在轻微色差或裁切差异——预览即你的确认依据。",
      "faq-q3": "退换政策是什么？",
      "faq-a3": "瑕疵或损坏：14 天内免费补发。定制商品非我方错误不支持退货。",
      "faq-q4": "有哪些尺寸？",
      "faq-a4": "迷你 5×6 cm（$7.99）、标准 8×10 cm（$11.99）、大号 12×15 cm（$16.99）。多件自动享折扣。",
      "faq-q5": "如何付款？",
      "faq-a5": "启用 Stripe 时支持安全卡支付；否则通过邮件确认订单与付款方式。",
      "faq-compare-link": "查看 River Magnets 竞品对比 →",
      "checkout-note": "提交订单即表示你同意我们的服务条款。我们将通过邮件联系你确认付款和发货详情。",
      "cookie-text": "我们使用Cookie来提升你的浏览体验。继续使用即表示你同意我们使用Cookie。",
      "cookie-accept": "接受",
      "privacy-link": "隐私政策"
    }
  };

  function getStoredLang() {
    try {
      return localStorage.getItem(LANG_KEY);
    } catch {
      return null;
    }
  }

  function setStoredLang(value) {
    try {
      localStorage.setItem(LANG_KEY, value);
    } catch {
      /* ignore */
    }
  }

  function applyLang(lang) {
    const langData = translations[lang] || translations[DEFAULT_LANG];
    
    document.querySelectorAll("[data-lang-key]").forEach(el => {
      const key = el.getAttribute("data-lang-key");
      if (langData[key]) {
        el.innerHTML = langData[key];
      }
    });

    document.querySelectorAll("[data-lang-attr]").forEach(el => {
      const parts = el.getAttribute("data-lang-attr").split("|");
      const attr = parts[0];
      const key = parts[1];
      if (langData[key]) {
        el.setAttribute(attr, langData[key]);
      }
    });

    document.documentElement.lang = lang;
    setStoredLang(lang);

    document.querySelectorAll(".lang-btn").forEach(btn => {
      btn.classList.toggle("lang-btn--active", btn.getAttribute("data-lang") === lang);
    });

    if (window.renderProductOptions) window.renderProductOptions();
  }

  const storedLang = getStoredLang();
  applyLang(storedLang || DEFAULT_LANG);

  document.querySelectorAll("[data-lang]").forEach(btn => {
    btn.addEventListener("click", () => {
      const lang = btn.getAttribute("data-lang");
      applyLang(lang);
      if (window.updateCartUI) window.updateCartUI();
    });
  });

  window.applyLang = applyLang;
  window.t = function (key) {
    const lang = getStoredLang() || DEFAULT_LANG;
    const langData = translations[lang] || translations[DEFAULT_LANG];
    return langData[key] || key;
  };
})();